apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-srv-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: film-srv:latest
          ports:
            - containerPort: 8080
